# array of regular expression strings to match workflow names
# which should be watched by bot
workflowWithTests = [
  '.*cypress.*', # all workflows with sub-string "cypress" in their names will be watched by bot
]
