name: Fake workflow

on:
  pull_request:
  push:
    branches:
      - '!master'

jobs:
  do-nothing-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Do nothing
        uses: cypress-io/github-action@v2
        with:
          command: echo 'I have done nothing'
