name: Screenshot tests all packages of Taiga UI

on:
  pull_request:
  push:
    branches:
      - '!master'

jobs:
  cy-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: BUTTONS
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          command: npm run test:buttons:ci

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: buttons-screenshots
          path: tests/cypress/snapshots
          retention-days: 7
  cy-tests-2:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: BADGES
          uses: cypress-io/github-action@v2
          with:
            start: npm run serve
            command: npm run test:badges:ci

        - name: Upload artifact
          uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: badges-screenshots
            path: tests/cypress/snapshots
            retention-days: 7
